name: "Windows Publish"

on:
  push:
    branches:
      - main

jobs:
  client-publish:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest]

    runs-on: {{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ github.token }}
